### ISSUE TITLE
taylor_plot seems to not normalize stdev by default

### ISSUE THREAD

**Issue by mnbucher** [rbischof/model_evaluation#1]
Haven't looked much into the core code yet, but by running the default interface `taylor_plot`, I get an empty taylor diagram with normalized stdev on the x-axis. Python prints some error that the values are out of axis limits and by printing the stdev (which is computed internally by `taylor_statistics`) this may be the issue, as I can't find any LOC normalizing it.

![Screenshot 2021-12-04 at 11 26 50](https://user-images.githubusercontent.com/10981880/144706292-3c217469-51c6-4a79-8443-a91561d2f798.png)

By replacing `sdev = [sdevr, sdevp];` with `sdev = [sdevr/sdevr, sdevp/sdevr];` in `taylor_statistics.py`, hence normalizing the stdev by the reference stdev, this seems to fix it by visual inspection, but I'm not sure if that is supposed to be like this?

![Screenshot 2021-12-04 at 11 27 19](https://user-images.githubusercontent.com/10981880/144706295-0874692b-fb8f-47ab-b8ef-e31770f492e3.png)

**Comment by rbischof** [comment]
You have 2 options:
- normalize the results before calling taylor_plot
- use unnormalized data but change the stddev axis range _axismax_ in taylor_plot

One could modify the function to select _axismax_ dynamically. Feel free to open a push request.

**Comment by mnbucher** [comment]
aight thx! :)
